<template>
  <div class="personal-datastore-container">
    <div v-if="!hasLoadedPersonalDatastore" class="max-w-3xl mx-auto">
      <nav class="mb-6" aria-label="breadcrumb">
        <ol class="flex items-center space-x-2 text-sm text-gray-600 dark:text-gray-400">
          <li class="flex items-center">
            <RouterLink to="/" class="flex items-center hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
              <i class="pi pi-table mr-1"></i>
              Catalog
            </RouterLink>
          </li>
          <li class="flex items-center">
            <i class="pi pi-angle-right mx-2 text-gray-400"></i>
            <i class="pi pi-database mr-1"></i>
            <span class="font-medium text-gray-900 dark:text-gray-100">Personal datastore</span>
          </li>
        </ol>
      </nav>

      <div class="bg-white dark:bg-gray-800 rounded-lg shadow-lg overflow-hidden">
        <div class="p-4 bg-gray-50 dark:bg-gray-700 border-b border-gray-200 dark:border-gray-600">
          <div class="flex items-center gap-2">
            <i class="pi pi-upload text-blue-600 text-xl"></i>
            <h1 class="text-lg font-semibold text-gray-900 dark:text-white">Explore my personal datastore</h1>
          </div>
        </div>

        <div class="p-6 space-y-5">
          <p class="text-gray-700 dark:text-gray-300">
            Upload the CSV generated by your intake-esm datastore workflow. The file stays in this browser session and
            replaces any previous personal datastore.
          </p>

          <div
            v-if="error"
            class="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg p-4"
          >
            <div class="flex items-center">
              <i class="pi pi-exclamation-triangle text-red-500 mr-2"></i>
              <span class="text-red-700 dark:text-red-300 font-medium">Could not load CSV:</span>
            </div>
            <p class="text-red-600 dark:text-red-400 mt-1">{{ error }}</p>
          </div>

          <label class="block">
            <span class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">Datastore CSV</span>
            <input
              type="file"
              accept=".csv,text/csv"
              class="block w-full text-sm text-gray-700 dark:text-gray-200 file:mr-4 file:rounded-md file:border-0 file:bg-blue-600 file:px-4 file:py-2 file:text-sm file:font-medium file:text-white hover:file:bg-blue-700"
              @change="onFileChange"
            />
          </label>

          <div
            v-if="warnings.length"
            class="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4"
          >
            <div class="flex items-center">
              <i class="pi pi-info-circle text-yellow-600 mr-2"></i>
              <span class="text-yellow-700 dark:text-yellow-300 font-medium">This CSV may still work, but:</span>
            </div>
            <ul class="mt-2 list-disc pl-5 text-yellow-700 dark:text-yellow-300">
              <li v-for="warning in warnings" :key="warning">{{ warning }}</li>
            </ul>
          </div>

          <div class="flex flex-col sm:flex-row gap-3">
            <Button
              label="Load CSV"
              icon="pi pi-database"
              :disabled="!selectedFile || loading"
              :loading="loading"
              @click="loadSelectedFile"
            />
            <RouterLink to="/" class="inline-flex">
              <Button label="Back to catalogue" icon="pi pi-arrow-left" outlined />
            </RouterLink>
          </div>
        </div>
      </div>
    </div>

    <div v-else>
      <div
        class="session-banner bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-6"
      >
        <div class="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
          <div>
            <div class="flex items-center">
              <i class="pi pi-info-circle text-blue-600 mr-2"></i>
              <strong class="text-blue-700 dark:text-blue-300">Personal datastore:</strong>
            </div>
            <p class="text-blue-700 dark:text-blue-300 mt-1">
              {{ catalogStore.personalDatastore?.csvFileName }} is available until this page is refreshed.
            </p>
          </div>
          <div class="flex flex-col sm:flex-row gap-3">
            <label class="inline-flex">
              <input type="file" accept=".csv,text/csv" class="hidden" @change="onReplacementFileChange" />
              <span
                class="inline-flex items-center justify-center gap-2 rounded-md border border-blue-600 px-3 py-2 text-sm font-medium text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/30 cursor-pointer"
              >
                <i class="pi pi-upload"></i>
                Replace CSV
              </span>
            </label>
            <Button label="Clear" icon="pi pi-times" outlined size="small" @click="clearPersonalDatastore" />
          </div>
        </div>
      </div>

      <EagerDatastoreDetail
        :datastore-name="catalogStore.personalDatastore?.name"
        :cache-key="catalogStore.personalDatastoreCacheKey"
        :auto-load="false"
        source="personal"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';
import Button from 'primevue/button';
import EagerDatastoreDetail from './eager/EagerDatastoreDetail.vue';
import { useCatalogStore } from '../stores/catalogStore';

const catalogStore = useCatalogStore();

const selectedFile = ref<File | null>(null);
const loading = ref(false);
const error = ref<string | null>(null);
const warnings = ref<string[]>([]);

const hasLoadedPersonalDatastore = computed(() => {
  return (
    catalogStore.hasPersonalDatastore &&
    catalogStore.getDatastoreFromCache(catalogStore.personalDatastoreCacheKey)?.data.length
  );
});

const onFileChange = (event: Event) => {
  const target = event.target as HTMLInputElement;
  selectedFile.value = target.files?.[0] ?? null;
  error.value = null;
  warnings.value = [];
};

const onReplacementFileChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0] ?? null;
  target.value = '';
  if (!file) return;
  selectedFile.value = file;
  await loadSelectedFile();
};

const loadSelectedFile = async () => {
  if (!selectedFile.value) return;

  loading.value = true;
  error.value = null;
  warnings.value = [];

  try {
    const cache = await catalogStore.replacePersonalDatastore(selectedFile.value);
    warnings.value = buildWarnings(cache.columns);
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Failed to load personal datastore';
  } finally {
    loading.value = false;
  }
};

const clearPersonalDatastore = () => {
  catalogStore.clearPersonalDatastore();
  selectedFile.value = null;
  error.value = null;
  warnings.value = [];
};

const buildWarnings = (columns: string[]) => {
  const recommendedColumns = ['file_id', 'variable', 'path', 'frequency', 'realm'];
  const missing = recommendedColumns.filter((column) => !columns.includes(column));
  return missing.map((column) => `Missing recommended column: ${column}`);
};
</script>

<style scoped>
.personal-datastore-container {
  width: 100%;
  max-width: calc(100vw - 4rem);
  margin: 0 auto;
  padding: 2rem;
}

.session-banner {
  max-width: calc(100vw - 4rem);
  margin-left: auto;
  margin-right: auto;
}

@media (max-width: 767px) {
  .personal-datastore-container {
    max-width: 100%;
    padding: 0.5rem;
  }

  .session-banner {
    max-width: 100%;
  }
}
</style>
