<template>
  <Dialog
    v-model:visible="visible"
    modal
    header="Welcome to the ACCESS-NRI Interactive Data Catalogue"
    :style="{ width: '52rem' }"
    :breakpoints="{ '768px': '95vw' }"
    class="mx-4 welcome-modal"
    @hide="onHide"
  >
    <!-- Intro paragraph -->
    <div class="mb-5 leading-relaxed space-y-3">
      <p class="text-gray-700 dark:text-gray-300">
        The <strong class="text-gray-900 dark:text-white">ACCESS-NRI Interactive Data Catalogue</strong> lets you find
        and explore <em>metadata</em> about climate and earth-system datasets available on
        <a
          href="https://nci.org.au/"
          target="_blank"
          rel="noopener noreferrer"
          class="text-blue-600 dark:text-blue-400 hover:underline"
          >NCI</a
        >'s Gadi supercomputer.
        <strong class="text-gray-900 dark:text-white">You will need an NCI account to access the data.</strong>
      </p>
      <p class="text-gray-700 dark:text-gray-300">
        Each entry in the catalogue describes an
        <a
          href="https://intake-esm.readthedocs.io/"
          target="_blank"
          rel="noopener noreferrer"
          class="text-blue-600 dark:text-blue-400 hover:underline"
          >intake-esm</a
        >
        datastore — a structured collection of model output or observational data you can load directly into Python on
        Gadi.
      </p>
      <p class="text-gray-700 dark:text-gray-300">
        Once you've found a datastore of interest, you can copy the autogenerated quickstart code snippet and open an
        <a
          href="https://are.nci.org.au/"
          target="_blank"
          rel="noopener noreferrer"
          class="text-blue-600 dark:text-blue-400 hover:underline"
          >ARE</a
        >
        session to start analysing the data in Python.
      </p>
    </div>

    <!-- Accordion with progressive detail -->
    <Accordion class="welcome-accordion">
      <!-- Panel 1: Getting around the catalogue -->
      <AccordionPanel value="using">
        <AccordionHeader>
          <span class="flex items-center gap-2">
            <i class="pi pi-compass text-blue-600"></i>
            Exploring the catalogue
          </span>
        </AccordionHeader>
        <AccordionContent>
          <ul class="space-y-3 text-sm text-gray-700 dark:text-gray-300 pl-1">
            <li class="flex items-start gap-2">
              <i class="pi pi-search text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                <strong class="text-gray-900 dark:text-white">Search all fields</strong> using the search box in the
                table header — it matches name, description, model, realm, frequency, and variable simultaneously.
              </span>
            </li>
            <li class="flex items-start gap-2">
              <i class="pi pi-filter text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                <strong class="text-gray-900 dark:text-white">Filter by category</strong> using the filter bar below the
                page header. Filters for Model, Realm, Frequency, and Variable interact with each other — only options
                that still yield results remain selectable.
              </span>
            </li>
            <li class="flex items-start gap-2">
              <i class="pi pi-table text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                <strong class="text-gray-900 dark:text-white">Show/hide columns</strong> with the column selector in the
                table header.
              </span>
            </li>
            <li class="flex items-start gap-2">
              <i class="pi pi-arrow-right text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                <strong class="text-gray-900 dark:text-white">Click any row</strong> to see a detailed view for that
                entry, including metadata, some high level datastore information, and a quick-start code snippet.
              </span>
            </li>
          </ul>
        </AccordionContent>
      </AccordionPanel>

      <!-- Panel 2: Using the data in Python -->
      <AccordionPanel value="python">
        <AccordionHeader>
          <span class="flex items-center gap-2">
            <i class="pi pi-code text-blue-600"></i>
            Using a datastore in Python
          </span>
        </AccordionHeader>
        <AccordionContent>
          <p class="text-sm text-gray-700 dark:text-gray-300 mb-3">
            Once you have found a datastore of interest, you may access it by executing the autogenerated quickstart
            code in an
            <a
              href="https://are.nci.org.au/"
              target="_blank"
              rel="noopener noreferrer"
              class="text-blue-600 dark:text-blue-400 hover:underline"
              >ARE</a
            >
            session. The quickstart code will load the data you have asked for as an
            <a
              href="https://docs.xarray.dev/en/stable/generated/xarray.Dataset.html"
              target="_blank"
              rel="noopener noreferrer"
              class="text-blue-600 dark:text-blue-400 hover:underline"
              >Xarray Dataset</a
            >.
          </p>
          <p class="text-sm text-gray-700 dark:text-gray-300 mb-2">For example:</p>
          <highlightjs language="python" :code="pythonSnippet" class="text-sm rounded-md overflow-hidden" />
          <div class="mt-2">
            <span class="text-xs font-semibold text-gray-400 dark:text-gray-500 uppercase tracking-wide">Output</span>
            <div
              v-html="xarrayReprHtml"
              class="xarray-repr-container mt-1 rounded-md overflow-x-auto border border-gray-200 dark:border-gray-700"
            />
          </div>
          <p class="text-xs text-gray-500 dark:text-gray-400 mt-2">
            See the
            <a
              href="https://access-nri-intake-catalog.readthedocs.io/"
              target="_blank"
              rel="noopener noreferrer"
              class="text-blue-600 dark:text-blue-400 hover:underline"
              >ACCESS-NRI Intake documentation</a
            >
            for full details on querying, subsetting, and loading data.
          </p>
        </AccordionContent>
      </AccordionPanel>

      <!-- Panel 3: About the catalogue -->
      <AccordionPanel value="about">
        <AccordionHeader>
          <span class="flex items-center gap-2">
            <i class="pi pi-info-circle text-blue-600"></i>
            About this tool
          </span>
        </AccordionHeader>
        <AccordionContent>
          <ul class="space-y-3 text-sm text-gray-700 dark:text-gray-300 pl-1">
            <li class="flex items-start gap-2">
              <i class="pi pi-database text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                This site serves <strong class="text-gray-900 dark:text-white"> only catalogue metadata</strong>, and
                runs queries in your browser. To access the data, you will need to be using NCI's Gadi supercomputer.
              </span>
            </li>
            <li class="flex items-start gap-2">
              <i class="pi pi-sync text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                The catalogue is updated automatically when new datastores are added to the ACCESS-NRI intake catalog.
              </span>
            </li>
            <li class="flex items-start gap-2">
              <i class="pi pi-github text-blue-500 mt-0.5 flex-shrink-0"></i>
              <span>
                Found a bug or have a suggestion? Click on the green
                <strong class="text-gray-900 dark:text-white">"Give us feedback"</strong> button in the page header to
                open a GitHub issue.
              </span>
            </li>
          </ul>
        </AccordionContent>
      </AccordionPanel>
    </Accordion>

    <template #footer>
      <div class="flex items-center justify-between w-full">
        <label class="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400 cursor-pointer select-none">
          <input
            type="checkbox"
            v-model="dontShowAgain"
            class="rounded border-gray-300 dark:border-gray-600 text-blue-600 focus:ring-blue-500"
          />
          Don't show this again
        </label>
        <Button label="Get started" icon="pi pi-arrow-right" icon-pos="right" @click="close" autofocus />
      </div>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import Dialog from 'primevue/dialog';
import Button from 'primevue/button';
import Accordion from 'primevue/accordion';
import AccordionPanel from 'primevue/accordionpanel';
import AccordionHeader from 'primevue/accordionheader';
import AccordionContent from 'primevue/accordioncontent';
import xarrayReprHtml from '../assets/xarray-repr.html?raw';
import { usePostHog } from '../composables/usePosthog';

const STORAGE_KEY = 'catalogue-welcome-seen';

const visible = ref(false);
const dontShowAgain = ref(false);
const { track } = usePostHog();

onMounted(() => {
  if (!localStorage.getItem(STORAGE_KEY)) {
    visible.value = true;
    track('welcome_modal_shown', { trigger: 'auto' });
  }
});

const onHide = () => {
  if (dontShowAgain.value) {
    localStorage.setItem(STORAGE_KEY, 'true');
    track('welcome_modal_dont_show_again');
  }
};

const close = () => {
  if (dontShowAgain.value) {
    localStorage.setItem(STORAGE_KEY, 'true');
    track('welcome_modal_dont_show_again');
  }
  visible.value = false;
};

/** Imperatively open the modal regardless of localStorage state. */
const open = () => {
  visible.value = true;
  track('welcome_modal_shown', { trigger: 'button' });
};

defineExpose({ open });

const pythonSnippet = `import intake
from dask.distributed import Client

client = Client(threads_per_worker=1)

datastore = intake.cat.access_nri["1deg_jra55_iaf_omip2spunup_cycle31"]
datastore = datastore.search(frequency='1mon')
datastore = datastore.search(realm='ocean')
datastore = datastore.search(variable='temp_surface_ave')
dataset = datastore.to_dask()
dataset`;
</script>

<style scoped>
:deep(.xarray-repr-container) {
  color-scheme: light;
  color: rgba(0, 0, 0, 1);
  background-color: white;
  /* Pin all xarray CSS variables to light-mode values.
     The repr's :root definitions use --jp-* / --pst-* variables that are
     never set in this app, the fallback for --xr-font-color0 has a broken
     comma, and the app's global dark-mode body styles bleed in.
     Overriding here ensures the repr always renders correctly. */
  --xr-font-color0: rgba(0, 0, 0, 1);
  --xr-font-color2: rgba(0, 0, 0, 0.54);
  --xr-font-color3: rgba(0, 0, 0, 0.38);
  --xr-border-color: hsl(0 0% 88%);
  --xr-disabled-color: hsl(0 0% 60%);
  --xr-background-color: white;
  --xr-background-color-row-even: hsl(0 0% 95%);
  --xr-background-color-row-odd: hsl(0 0% 85%);
}

:deep(.welcome-accordion .p-accordionpanel) {
  border: 1px solid #e5e7eb;
  border-radius: 0.5rem;
  margin-bottom: 0.5rem;
  overflow: hidden;
}

:deep(.welcome-accordion .p-accordionheader) {
  background-color: #f9fafb;
  padding: 0.75rem 1rem;
  font-weight: 600;
  color: #111827;
}

:deep(.welcome-accordion .p-accordionheader:hover) {
  background-color: #f3f4f6;
}

:deep(.welcome-accordion .p-accordioncontent-content) {
  padding: 1rem;
  background-color: #ffffff;
}

@media (prefers-color-scheme: dark) {
  :deep(.welcome-accordion .p-accordionpanel) {
    border-color: #374151;
  }

  :deep(.welcome-accordion .p-accordionheader) {
    background-color: #1f2937;
    color: #f9fafb;
  }

  :deep(.welcome-accordion .p-accordionheader:hover) {
    background-color: #374151;
  }

  :deep(.welcome-accordion .p-accordioncontent-content) {
    background-color: #111827;
  }
}
</style>
